# Generated by Django 3.1.1 on 2020-09-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='date',
        ),
    ]
