# Generated by Django 3.1.1 on 2020-09-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.TextField()),
                ('images', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
